### ISSUE TITLE
Limit range of Advanced Panel

### ISSUE THREAD

**Issue by Learting** [BentoBoxWorld/Biomes#111]
### Is your feature request related to a problem?

Some annoying players applied for a huge amount of chunk range in changing biome, making the queue too long. So I really wanted to have a "limit" setting in advanced panel, to limit their choice.

### Describe the solution you'd like.

Make a setting in the config, enabling the limit of chunk range that players can choose in the advanced panel.

### Describe alternatives you've considered.

/

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
I will think about it but currently, you can set players can change biome only in the island protection area. It should reduce a lot of change time if your protection range is significantly smaller than the distance between islands.

**Comment by Learting** [comment]
> I will think about it but currently, you can set players can change biome only in the island protection area. It should reduce a lot of change time if your protection range is significantly smaller than the distance between islands.

Thank you for your reply. Yes, but I set a relatively high protection range value which is 1024, for some special survival players are building mega structures and complex automatic production machines. Apparently, BentoBox does not support multi islands yet, so they build on one island. While some noobs does not know about the cost of changing biome, they just make a fairly large number, lagging the waiting queue until time out. It can be quite annoying when many players are making dumb requests.
