### ISSUE TITLE
Biomes doesn't change

### ISSUE THREAD

**Issue by TheCasualTw** [BentoBoxWorld/Biomes#118]
### Expected behavior

Changing biomes

### Observed/Actual behavior

When I change biomes, or set a biome via an admin command, it stays in the queue and nothing happens

### Steps/models to reproduce

Use: oba biomes set (username) frozen_water CHUNK 1
Look my screens:
https://media.discordapp.net/attachments/310623455462686720/1103768172659748905/image.png?width=1485&height=93

no error: https://cdn.discordapp.com/attachments/310623455462686720/1103755564703551590/image.png

### BentoBox version

1.20.1

**Comment by tastybento** [comment]
Can you give the output of `bbox version` so we can try and replicate this?

Also, just to clarify, if you log out and back in again the biome has not changed?
