### ISSUE TITLE
Biome change not recognizing bucket of self caught fish

### ISSUE THREAD

**Issue by thunderlight411** [BentoBoxWorld/Biomes#123]
### Expected behavior

We expect that when a player does have a bucket of tropical fish in his inventory we is able to change the biome.

This only works when a bucket came from a wandering trader.
When he caught the fish him self in a bucket its not recognised by the plugin

### Observed/Actual behavior

Self caught bucket contains aditional NBT data with the type of fish. when this is present the biome change wont recognize the item

### Steps/models to reproduce

caught a tropical fish and try to use it by changing the biome

### BentoBox version

09.06 12:30:00 [Server] INFO Running PAPER 1.19.4.
09.06 12:30:00 [Server] INFO BentoBox version: 1.23.1
09.06 12:30:00 [Server] INFO Database: JSON
09.06 12:30:00 [Server] INFO Loaded Game Worlds:
09.06 12:30:00 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
09.06 12:30:00 [Server] INFO Loaded Addons:
09.06 12:30:00 [Server] INFO Bank 1.5.0 (DISABLED)
09.06 12:30:00 [Server] INFO Biomes 2.1.1 (ENABLED)
09.06 12:30:00 [Server] INFO BSkyBlock 1.16.1 (ENABLED)
09.06 12:30:00 [Server] INFO Challenges 1.2.0 (ENABLED)
09.06 12:30:00 [Server] INFO ControlPanel 1.13.0 (ENABLED)
09.06 12:30:00 [Server] INFO DimensionalTrees 1.6.0 (ENABLED)
09.06 12:30:00 [Server] INFO Level 2.10.0 (ENABLED)
09.06 12:30:00 [Server] INFO Warps 1.13.0 (ENABLED)

### Plugin list

9.06 12:30:04 [Server] INFO Server Plugins (27):
09.06 12:30:04 [Server] INFO Bukkit Plugins:
09.06 12:30:04 [Server] INFO - BentoBox, BentoBox-Bank, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Warps, BungeeTabListPlus, CMI, CMILib
09.06 12:30:04 [Server] INFO CoreProtect, dynmap, FreedomChat, ImageMaps, *IPWhitelist, JustTitle, LuckPerms, MaintenanceAddon, MultiChat, PlaceholderAPI
09.06 12:30:04 [Server] INFO Plan, spark, UltimateVotes, Vault, ViaVersion, WorldEdit, WorldGuard

### Other

09.06 12:30:08 [Server] INFO This server is running Paper version git-Paper-549 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bc4a664)
![Bbox_biomes_Tropical_Fish](https://github.com/BentoBoxWorld/Biomes/assets/4320849/838f7db7-827b-46c7-a2c4-0428d86d4b40)

**Comment by SirvydasS** [comment]
Having same problem :(
