### ISSUE TITLE
Biome Change Cost review

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Biomes#14]
#### Is your feature request related to a problem? Please describe.
Currently users can change biomes in any size just for single price. Why not to add possibility to specify, that cost is per block?

#### Describe the solution you'd like
Cost to change biome can be calculated in 3 ways:
- per block (cost will be multiplied by block count)
- per usage (current behavior)
- per biome change count (each time changing biome will be more expensive by cost increment)

#### Additional context
None

**Comment by TheWranger** [comment]
per biome change count would be very useful since players generally obtain bigger farms that will bring in more money, by increasing biome every time the island biome is changed it means that more money will be taken out of the playerbase whist only enforcing this on older players.
