### ISSUE TITLE
Money issue with BIOMES

### ISSUE THREAD

**Issue by Hechers** [BentoBoxWorld/Biomes#142]
### Is your feature request related to a problem?

Bento send me here because I have an issue with the prices of the biomes. In the config its set to an amount bu in-game its showing up as $1.0E8 

Economy I use is Vault

![image](https://github.com/user-attachments/assets/6964eb9a-b56a-41c5-83b5-35ab80d8e48c)
![image](https://github.com/user-attachments/assets/6d072aaf-cbcd-40b0-a8c5-4832eeec18c5)

![image](https://github.com/user-attachments/assets/3cba1799-4f3f-45d8-b641-ecb05cc7a530)

### Describe the solution you'd like.

That the amount what I set in the config shows up in-game. or someone who can tell me whats wrong

### Describe alternatives you've considered.

I reset the config but no help.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
The snapshot should fix this. Please try it.

**Comment by tastybento** [comment]
You may need to update your language file to remove the $ sign from it because Vault may add one.
