### ISSUE TITLE
Cost and Level Requirement in GUI

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/Biomes#18]
**Is your feature request related to a problem? Please describe.**
Players currently can't see the level requirement or cost of a biome without attempting to change to that biome, very inconvenient for players.

**Describe the solution you'd like**
Display the biome cost and the level requirement in the lore of the biome icon. If the cost is set to 0 or level requirement are set to 0 then they should not be displayed in the GUI in order to keep it tidier.

**Comment by BONNe** [comment]
Hi,
Yes, I will add it in next version.

**Comment by TheWranger** [comment]
Yes, it's much more convenient to have it in the GUI though.

**Comment by BONNe** [comment]
Implemented.
