### ISSUE TITLE
Set a biome outside of island range

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/Biomes#26]
#### Describe the solution you'd like
For players who are not with in the island zones range to set boimes (skygrid) 

#### Describe alternatives you've considered
Not letting players set biomes :(

#### Additional context
The way i run the skygrid gamemode is that the players are not in the island range they never do /sg and get taken away  so they wont be in a zone to be able to use the biomes features.

**Comment by BONNe** [comment]
Implemented
