### ISSUE TITLE
Biome GUI is empty

### ISSUE THREAD

**Issue by AsqhalPayvey** [BentoBoxWorld/Biomes#27]
#### Description
When executing a biome change command on server, the gui is empty,

####  Steps to reproduce the behavior:
1. Go to your island
2. Type command for biome changes
4. And see the GUI show empty

#### Expected behavior
when using this command, the biome GUI displays several biome options to change the biome

#### Screenshots or video

https://imgur.com/a/As838NR

#### Server Information:
 - Database being used (YAML, JSON, MySQL, MongoDB): MySQL
 - OS: Ubuntu
 - Java Version: 8
 - BentoBox version: 1.4.0
 - Addons installed? https://imgur.com/a/XEy8oMu

**Comment by BONNe** [comment]
Could you try to use bsb biomes import?

**Comment by BONNe** [comment]
Could you try to use bsb biomes import?

**Comment by BONNe** [comment]
Set up better messages so admins could know what is happening.
Do not open gui if Biome list will be empty.
