### ISSUE TITLE
Translation lines

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Biomes#29]
#### Description
Translation lines of the biome is not displayed. As if the translation does not exist.

####  Steps to reproduce the behavior:
1. execute /is biomes help
2. See result

#### Screenshots or video
![Screenshot_20190524_111927](https://user-images.githubusercontent.com/28690790/58318145-7f80b600-7e17-11e9-8d14-05674578c8bd.png)

#### Server Information:
[Please complete the following information:]
Running PAPER 1.13.2.
BentoBox version: 1.5.0-SNAPSHOT-b1081
Loaded Game Worlds:
bskyblock_world (BSkyBlock)
Loaded Addons:
Biomes 1.5.0.0-SNAPSHOT-b64
BSkyBlock 1.5.0-b283
Challenges 0.7.5-SNAPSHOT-b212
Level 1.5.0-SNAPSHOT-b174
Limits 0.2.0-SNAPSHOT-b110
MagicCobblestoneGenerator 1.5.0.1-b18

**Comment by BONNe** [comment]
You need to reload a language package.
To do it, you need to delete /plugins/bentobox/locals folder and reload bentobox or restart server.

**Comment by x1p** [comment]
I have. Translated every part. But, this concerns English too.

**Comment by BONNe** [comment]
Biomes 1.5.0.0 changed all translation strings. If you were using a previous one, then they are not valid anymore. You need to delete existing biomes translation, so it could regenerate to new ones.

**Comment by x1p** [comment]
Ah. Clear now :+1:
