### ISSUE TITLE
Biome reset when user with biomes perm leave the island

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/Biomes#3]
_From @Poslovitch on March 29, 2017 18:48_

_From @YellowZaki on August 7, 2015 18:46_

In my server, VIP users have the perms to change their biomes and they can live with other users (being leaders), change their biome and leave the island. So I would like that when an island leader who has the perm to change biomes use /is makeleader user, the biome of the island get reset to the default biome.

_Copied from original issue: tastybento/askyblock#69_

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#73_

**Comment by BONNe** [comment]
This is implemented and can be tested in 0.4.0-SNAPSHOT build.
