### ISSUE TITLE
Control by an API

### ISSUE THREAD

**Issue by Manicraft1001** [BentoBoxWorld/Biomes#30]
**Is your feature request related to a problem? Please describe.**

With this biome addon you can set the biome of an island by GUI or command.
If you want to make an own addon and just use an easy api, you stuck.

**Describe the solution you'd like**
Great would be an API class for Island Biomes.
An void for setting the biome and a return wich returns the biome.

**Comment by BONNe** [comment]
Inside BentoBox hierarchy (by creating addon) you can use BiomeUpdateHelper to change Biome.

But I also add the ability to change biome with RequestHandler. Documentation will be soon in Wiki.
(@Poslovitch :D you like to document, here is your chance)
