### ISSUE TITLE
/is biomes results in an error. 

### ISSUE THREAD

**Issue by robbiemcleod56** [BentoBoxWorld/Biomes#33]
#### Description
Biomes doesn't work anymore. 

####  Steps to reproduce the behavior:
1. Go to your island, /is. 
2. Type /is biomes
3. See error

#### Expected behavior
To get biomes GUI like your instructions page says. 

#### Screenshots or video
![image](https://user-images.githubusercontent.com/7958152/59551297-7df16c00-8f45-11e9-971a-e5a5bd982a76.png)

#### Server Information:
[Please complete the following information:]
 - Database being used: [MySQL]
 - OS: [Windows 10]
 - Java Version: [Java 8]
 - BentoBox version: [e.g. 1.5.1]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
![image](https://user-images.githubusercontent.com/7958152/59551308-a9745680-8f45-11e9-9686-8364c4053ed9.png)
 - Other plugins? [Do '/plugins' and copy/paste from the console]
![image](https://user-images.githubusercontent.com/7958152/59551311-b729dc00-8f45-11e9-8551-9be3d92062ca.png)

Biomes GUI simply doesn't work.

**Comment by robbiemcleod56** [comment]
Aye. So sorry. Pressed the enter button by accident.

**Comment by robbiemcleod56** [comment]
Also didn't notice until now but your placeholders for CaveBlock's versions don't seem to be working.

**Comment by BONNe** [comment]
Update Lang files (by removing locales/biomes folder).
You will see then whole error.

And you should import biomes as for some reason they are not imported.

**Comment by robbiemcleod56** [comment]
Ah. Updating the locales helped. Now this appears. (already erased biomes folder, got new files)
![image](https://user-images.githubusercontent.com/7958152/59552100-93b85e80-8f50-11e9-97ef-1e9801700baa.png)

**Comment by BONNe** [comment]
./bsb biomes import
./cba biomes import

**Comment by robbiemcleod56** [comment]
Oh wow. Thanks guys. I assume you have to do that with every update? Perhaps the plugin should scan that automatically at startup?
