### ISSUE TITLE
Biomes must be re-imported after Beta-1 uptade

### ISSUE THREAD

**Issue by plagoutte** [BentoBoxWorld/Biomes#38]
After updating to Biomes beta 1, players can't use the `/is biomes` command (internal server error).

Use `/bsbadmin biomes import overwrite` fixed my problem, but you should  specify it in the changelog.

**Comment by BONNe** [comment]
No, it should not be default behaviour and it is a bug, that should be fixed in the development build.

**Comment by plagoutte** [comment]
I agree with you, but **currently**, it's a beta addon, and you should teach users how to upgrade it in the appropriate changelog. 

When Biomes addon will release a stable version, you can actually delete this indication.
