### ISSUE TITLE
Gui's biomes doesn't work

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/Biomes#40]
#### Description
The biomes can't be apply to island with the gui :(
But it works with /is biomes set ... and /bsadmin biomes set ...
I saw that message : "Cannot find biome with given ID 'ASkyBlock-<<biome>>"

####  Steps to reproduce the behavior:
1. /is biomes
2. Chooses a biome.
3. Accept

#### Server Information:
 - Database being used YAML: []
 - BentoBox version: 1.5.3
 - Addons installed? 
Biomes 1.5.0.0
BSkyBlock : 1.5.0
Challenges : 0.8.0-SNAPSHOT-#275
WelcomeWarps: 1.5.0
Level: 1.5.0

**Comment by BONNe** [comment]
Fixed in [Build #123](https://ci.codemc.org/job/BentoBoxWorld/job/Biomes/123/)
