### ISSUE TITLE
Please let the component support Chinese！

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/Biomes#41]
Hope that biome addons can support Chinese language

**Comment by BONNe** [comment]
Sorry, I do not know Chinese at all.
Somebody need to translate it.

**Comment by BackWheel** [comment]
I tried to make a translated text, but I want to know what role the order button of the island biome set in the Admin Menu in the component.

**Comment by BackWheel** [comment]
I can't translate the language of this button with my understanding... I hope I can get a detailed answer.

**Comment by BackWheel** [comment]
I will also translate the challengen component when I have time, but I don't want to modify the language file often.

**Comment by BackWheel** [comment]
I have completed the Chinese translation of biome, and you have to add this language file to the plugin, thank you!
[zh-CN.zip](https://github.com/BentoBoxWorld/Biomes/files/3342580/zh-CN.zip)

**Comment by BackWheel** [comment]
@BONNe

**Comment by BONNe** [comment]
Added in [build #123](https://ci.codemc.org/job/BentoBoxWorld/job/Biomes/123/)
