### ISSUE TITLE
Request to add a traditional Chinese language file

### ISSUE THREAD

**Issue by BackWheel** [BentoBoxWorld/Biomes#42]
Hey! Today I have a traditional Chinese translation of biome addon, I hope this will help more people!

[zh-TW.zip](https://github.com/BentoBoxWorld/Biomes/files/3342865/zh-TW.zip)

**Comment by tastybento** [comment]
@BONNe Want to add it?

**Comment by BONNe** [comment]
I will add it.
I just did not manage to do it yesterday :)
