### ISSUE TITLE
Biomes settings

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/Biomes#44]
Hello, biomes settings appears as available for everyone by default in /is settings from visitor to owner which is kind of non sense to me, there is no biomes flags in the config so i'm unable to set the default use,
regards.

![2019-08-18_13 14 05](https://user-images.githubusercontent.com/30918460/63223689-17453480-c1ba-11e9-99c0-25f9e9154245.png)

**Comment by BONNe** [comment]
Sorry, I am not willing to implement any new config options just in Biomes addon. It will become messy and each new flag will require adding new options in a file just so users could edit them.

I would prefer for this option to be edited in BentoBox core. f.e. like I suggest in this pull-request (https://github.com/BentoBoxWorld/BentoBox/pull/916)

**Comment by Nedjii** [comment]
I didn't asked any config, i'm reporting a non sense issue, why has everyone the permission to change an is biome ??

**Comment by BONNe** [comment]
Sorry :D 

I did not read it correctly :D

**Comment by BONNe** [comment]
Set it to default values. (member I  assume).

But you can define it in the config file as other flags, by using strings as they are locales file.
