### ISSUE TITLE
Biomes visibility - "biomes.gui.descriptions.admin.visibility-mode.info" shows

### ISSUE THREAD

**Issue by LordSheep** [BentoBoxWorld/Biomes#46]
#### Description
When doing /is biomes and you hover over island visibility you can see "biomes.gui.descriptions.admin.visibility-mode.info"
![image](https://user-images.githubusercontent.com/30538383/64130369-d8090d00-cd8f-11e9-80f4-8efa7826b791.png)

![image](https://user-images.githubusercontent.com/30538383/64130480-80b76c80-cd90-11e9-9c19-80257b708504.png)

#### Expected behavior
"biomes.gui.descriptions.admin.visibility-mode.info" to not show.

#### Server Information:
- BentoBox version: [e.g. 1.7.2.21]
![image](https://user-images.githubusercontent.com/30538383/64130738-42bb4800-cd92-11e9-8ad4-904801689e28.png)

####  Additional context
Maybe its from the biomes locale. Don't know where the ".info" from"biomes.gui.descriptions.admin.visibility-mode.info" came from.
![image](https://user-images.githubusercontent.com/30538383/64130572-2e2a8000-cd91-11e9-95c1-19a4e7614f48.png)

Also a question, I only put these permissions for biomes addon for default players
    - bskyblock.biomes
    - bskyblock.biomes.info
    - bskyblock.biomes.set 
but players are able to see "Biomes Visiblity" item.
Is that a bug or is that something regular players are meant to be able to see?

**Comment by BONNe** [comment]
Fixed in latest snapshot.
