### ISSUE TITLE
Still a problem with Biomes Cooldown

### ISSUE THREAD

**Issue by Waterman1001** [BentoBoxWorld/Biomes#48]
#### Description
Cooldowns on Switching Biomes are still not properly applied? :/

#### Server Information:
06.09 17:52:01 [Server] Server thread/INFO Running SPIGOT 1.14.4.
06.09 17:52:01 [Server] Server thread/INFO BentoBox version: 1.7.0-SNAPSHOT-b1359
06.09 17:52:01 [Server] Server thread/INFO Database: JSON
06.09 17:52:01 [Server] Server thread/INFO Loaded Game Worlds:
06.09 17:52:01 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
06.09 17:52:01 [Server] Server thread/INFO Loaded Addons:
06.09 17:52:01 [Server] Server thread/INFO Biomes 1.6.0.2-SNAPSHOT-b139 (ENABLED)
06.09 17:52:01 [Server] Server thread/INFO BSkyBlock 1.6.0-SNAPSHOT-b440 (ENABLED)
06.09 17:52:01 [Server] Server thread/INFO Challenges 0.8.0-SNAPSHOT-#347 (ENABLED)

####  Additional context
I already opened an issue on this but it is closed now.
And yes, I am using the latest Snapshot of Biomes Addon

**Comment by BONNe** [comment]
You do not need to create new issue. You can write that is still not working and I would reopen ;).

And I think now it should be checked. 
For some reason, checkCoolDown is not applied by default.

**Comment by Waterman1001** [comment]
Okay, Thank you very much! :D 
Also for the information and the quick response / support!

**Comment by Waterman1001** [comment]
For some reason, setting a biome is now not possible at all anymore...

I don't know whether this is maybe because before updating to the latest build I changed my biome.
I also don't know whether it is possible to see how long I have to wait?

Anyway, I cannot change my biome at all anymore with the latest build :S

**Comment by BONNe** [comment]
Sorry, it is friday... 
should be fixed now

**Comment by Waterman1001** [comment]
Yay!
Good job :D
Works now! :)

**Comment by BONNe** [comment]
sorry, I am tired.. made mistakes ...
