### ISSUE TITLE
Change user biome in end and nether

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/Biomes#51]
#### Is your feature request related to a problem? Please describe.
/bsb biomes - choose change user biome in end or nether. Now biomes changes only in overworld. 

#### Describe the solution you'd like
When you select user from the list then opens tab where you select which biome to change (overworld, nether, end)

**Comment by BONNe** [comment]
Just a question...
Which biomes do you want to set in the nether and in the end?

In some sort, it just does not make any sense to allow biomes changing in these worlds.

**Comment by tastybento** [comment]
We do have an addon called Greenhouses that enables players to make their own Biomes in these worlds inside glasshouses. That may be another option for OP.

**Comment by SirvydasS** [comment]
Yeah, maybe is not very necessary feature. It was my mistake dont block /is biomes in nether and players has change biome in nether (example to plains) and I dont grant permission change back to nether biome. When i block that cmd I try change player biome. I and player was in the nether and when i change biome it was changed in the overworld and spawn a lot of ghast in the main island 😁

**Comment by BONNe** [comment]
Ok, i will fix admin biome setting in nether/end
Also i will change default behaviour for environment to be overwold.

However, no eta. Asap

**Comment by x1p** [comment]
I have the opposite problem. By default, a player can change biomes in e.g. the nether.

Using Biomes-1.6.0.1-SNAPSHOT-b149
