### ISSUE TITLE
Unable to have players change biomes

### ISSUE THREAD

**Issue by Talidorn** [BentoBoxWorld/Biomes#53]
#### Description
perms added to PEX (island.biome.*).  Players can't change biomes

####  Steps to reproduce the behavior:
1. Add perm to pex (island.biome.*)
2. PEX reload
3. in client player uses /island biome and the pastebin below happens.

#### Expected behavior
Player should be able to change biome.

#### Screenshots or video
https://pastebin.com/sE0YTFCt

#### Server Information:
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Comment by BONNe** [comment]
Can you provide output of `/bentobox version` command?

**Comment by Talidorn** [comment]
21.10 09:16:48 [Server] Server thread/INFO Running SPIGOT Invalid.
21.10 09:16:48 [Server] Server thread/INFO BentoBox version: 1.5.3
21.10 09:16:48 [Server] Server thread/INFO Loaded Game Worlds:
21.10 09:16:48 [Server] Server thread/INFO acidisland_world (AcidIsland): Overworld, Nether, End
21.10 09:16:48 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
21.10 09:16:48 [Server] Server thread/INFO Loaded Addons:
21.10 09:16:48 [Server] Server thread/INFO AcidIsland 1.5.0 (ENABLED)
21.10 09:16:48 [Server] Server thread/INFO BentoBox-InvSwitcher 0.0.1-SNAPSHOT (ENABLED)
21.10 09:16:48 [Server] Server thread/INFO Biomes 1.5.0.0 (ENABLED)
21.10 09:16:48 [Server] Server thread/INFO BSkyBlock 1.5.0 (ENABLED)
21.10 09:16:48 [Server] Server thread/INFO Challenges 0.7.5 (ENABLED)
21.10 09:16:48 [Server] Server thread/INFO Level 1.5.0 (ENABLED)

**Comment by BONNe** [comment]
There was a bug in 1.5.0 release.
It can be fixed by removing all biomes and readding them back.
If you use default biomes, you can try with `/bsb biomes import overwrite` and `/acid biomes import overwrite`
It could help.
In 1.6.0 release I add a new command that does it, but it requires BentoBox 1.6.0.

**Comment by Talidorn** [comment]
I tried the command above and I still get the same issue.

I'm willing to upgrade bento and addons... I'm just not sure how it will impact my running server and islands.

If I stop the server, wipe the database entries for biomes and then import... might that work?

**Comment by BONNe** [comment]
You can try that. Probably, `overwrite` cannot overwrite something :(

**Comment by tastybento** [comment]
I don't think this is actionable so I'm closing.
