### ISSUE TITLE
Chunks being unloaded when they shouldn't be unloaded

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/Biomes#60]
@BONNe 

I think that there is a race condition where chunks can get unloaded by this code when they shouldn't be:
https://github.com/BentoBoxWorld/Biomes/blob/2cecc59954b4693488e3a8c0cbce78b679588788/src/main/java/world/bentobox/biomes/listeners/ChunkLoadListener.java#L75

We've received server crash bugs that are caused by unloaded chunks:
https://github.com/BentoBoxWorld/BentoBox/issues/1250

The issue is that just because the chunk is in the list of chunks to update, i.e, `getPendingChunkUpdateObject` returns non-null, doesn't mean that it should be unloaded. 

For example, let's say that Biomes has a set of chunks that it needs to set the biome for, but they are unloaded. The player teleports to one of these chunks, let's say by dying, and the `ChunkLoadEvent` fires. Your code checks that the chunk needs the biome set, so it does that and then unloads the chunk. The player is now in an unloaded chunk area and the server crashes.

Do you agree? I'll make a PR to prevent the chunks from being unloaded.

**Comment by BONNe** [comment]
Ok, I agree that there could be situations when chunks should not be unloaded. 
However, I added that part of code, because it loaded too many chunks in the world.
But we can disable and check how 1.15 and 1.16 handles chunk unloading, and probably there should not be any issue with too many opened chunks.

**Comment by tastybento** [comment]
Yes, I was thinking about that, but unless you active load chunks (do you?) it should just change the biome when they are loaded naturally and then unload them too.
