### ISSUE TITLE
Add config option to restrict setting biomes to certain worlds

### ISSUE THREAD

**Issue by lekro** [BentoBoxWorld/Biomes#62]
#### Is your feature request related to a problem?

Users can currently use `/is biomes` to change their Nether island to some non-nether biome, and can't change it back. We would like to be able to restrict changing island biomes only to the overworld, and send an appropriate error message to the user if biomes have been disabled in the user's current world.

#### Describe the solution you'd like us to implement.

Adding a configuration option of e.g. `disable-worlds: [skyblock_nether, skyblock_the_end]` would solve this problem. Anything similar, like something to disable in nether worlds or end worlds would work as well, as would having an `enable-worlds` option.

#### Describe alternatives you've considered.

The current workaround is to use world-specific permissions, for example using the command

`/lp group default permission set bskyblock.biomes false server=skyblock world=skyblock_nether`

which will work, but give a slightly misleading message about missing `bskyblock.biomes` permission when `/is biomes` is executed from the nether. We could further implement some other hacks to give a less misleading message, but it would be better to simply have the Biomes addon itself emit an appropriate message when it is disabled in a particular world.

**Comment by tastybento** [comment]
I think this is actually a bug. If players can change the biome in the nether but not change it back then that would be a bug. The proposal to limit biome changing to just the overworld makes sense to me. I'd like @BONNe to give his thoughts.

**Comment by BONNe** [comment]
As 1.16 is coming, then no, I disagree.
However, I would like to split biomes by correct dimension.

**Comment by tastybento** [comment]
Ah, that makes sense.
