### ISSUE TITLE
Locale error

### ISSUE THREAD

**Issue by mikesonchan** [BentoBoxWorld/Biomes#65]
#### Describe the bug

Information shows "biomes.gui.descriptions.update-mode.range" when choosing "Range".
#### Steps to reproduce the behavior

1. Open biome change GUI
2. Choose biome
3. Choose "Range"
4. See "Information"
#### Expected behavior

It should show the string "Range".
#### Screenshots and videos (Optional)

https://imgur.com/w8fI8nt
##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.12.0
Database: JSON
Loaded Game Worlds:
ASkyBlock (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
Loaded Addons:
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.12.0 (ENABLED)
Challenges 0.8.1 (ENABLED)
Level 1.9.3 (ENABLED)
Limits 1.9.4 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.3 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
Quick fix, change you locale file to be like this:
```
      update-mode:
        island: "Island"
        chunk: "Chunk"
        range: "Range"
        undefined: "Undefined"
```

This issue is caused by Line 319 of UpdateModeGUI.java:
```
						"[mode]", this.user.getTranslation("biomes.gui.descriptions.update-mode." + this.updateMode.name().toLowerCase()),
```
The enum name values for UpdateMode are:

		ISLAND,
		CHUNK,
		RANGE;

So, the locale key must be range, not "square". This can be fixed.

**Comment by tastybento** [comment]
@BONNe Do you recommend changing all the locales to just use `range:` or do you prefer some code to turn the enum into `square`?

**Comment by BONNe** [comment]
Square comes from old code. It was changed to range, but I think I missed this one
