### ISSUE TITLE
Changing biome in range mode will become an irregular shape

### ISSUE THREAD

**Issue by mikesonchan** [BentoBoxWorld/Biomes#66]
#### Describe the bug

Changing biome in range mode will become an irregular shape.
#### Steps to reproduce the behavior

1. Open biome change GUI
2. Choose biome
3. Choose "Range"
4. Change value
5. Click "Accept"
6. Reenter the island
#### Expected behavior

Changed biome should be a square.
#### Screenshots and videos (Optional)

Gold block is the center and grass blocks are the changed biome.
https://www.youtube.com/watch?v=Uku3HR4mxZ8
##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.13.1
Database: JSON
Loaded Game Worlds:
ASkyBlock (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
Loaded Addons:
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.13.1 (ENABLED)
Challenges 0.8.2 (ENABLED)
IslandFly 1.7.3 (ENABLED)
Level 2.0.0 (ENABLED)
Limits 1.12.2 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.9.5 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
On your island do `/is info` and share the output, or in the console do `bsb info (your name)` and share the info.

**Comment by tastybento** [comment]
I checked and Biomes is definitely only setting the biome for the 5x5 box but in Minecraft now Biomes cannot be set on block boundaries. This seems like a Spigot bug, so I filed this issue: https://hub.spigotmc.org/jira/browse/SPIGOT-5772

**Comment by tastybento** [comment]
We received closure from the Spigot team - this effect is vanilla operation, so we cannot do anything, sorry:

> Biomes are stored for a 4*4*4 cube. Minecraft then blends those biomes together. So it's technically stored for that cube, but might appear larger depending on surrounding biomes.
There is nothing that could be done on the Spigot side. If you think you know a better solution to biome blending, please use the Mojang bug tracker.
