### ISSUE TITLE
Ability to change title

### ISSUE THREAD

**Issue by daoshii** [BentoBoxWorld/Biomes#68]
### Description
The title at the top of the biome menu is orange. I was able to change my other menus just not this one, It is a bit harder to read too. It would be nice to choose our own!
#### Is your feature request related to a problem?
no

#### Describe the solution you'd like us to implement.
Allow us to customize menu title

### Additional context
![choosebiome](https://user-images.githubusercontent.com/61712934/85794297-f9aafa80-b6fb-11ea-9e36-29695bbfd4ba.jpg)

**Comment by tastybento** [comment]
All the text can be customized in the locale files. Go to `/plugins/BentoBox/locales/Biomes` and edit the file. See https://github.com/BentoBoxWorld/Biomes/blob/develop/src/main/resources/locales/en-US.yml for an example.
