### ISSUE TITLE
Biomes vs Greenhouses

### ISSUE THREAD

**Issue by KlayaR** [BentoBoxWorld/Biomes#80]
I just saw that you worked on the biomes vs greenhouses situation. Thank you so much for that.

Now, as you can see on my screenshot, the biome indeed stayed jungle above the ground, but the actual ground changed into snowy tundra. A note, this is purely aesthetic, the greenhouse is working as it should. 
![image](https://user-images.githubusercontent.com/53836029/94314539-fa645e80-ff80-11ea-8408-b9fe984ec956.png)

**Comment by BONNe** [comment]
In the latest dev version, this should not happen anymore

**Comment by KlayaR** [comment]
Of course

Version: 
![image](https://user-images.githubusercontent.com/53836029/94336476-cec69000-ffe3-11ea-8332-370cb64a2a1d.png)

Biome in Greenhouse:
![image](https://user-images.githubusercontent.com/53836029/94336952-18fd4080-ffe7-11ea-8e05-845b08f61248.png)

Biome in the ground bellow the greenhouse
![image](https://user-images.githubusercontent.com/53836029/94336968-303c2e00-ffe7-11ea-8c1b-11ba00e8c195.png)


In fact I actually get something looking like this after using is biome: 
![image](https://user-images.githubusercontent.com/53836029/94337022-9b860000-ffe7-11ea-9859-0eb54107684a.png)

**Comment by KlayaR** [comment]
Feel free to add me on discord so I can whitelist you on my server if you want to check it out. Might be easier

**Comment by KlayaR** [comment]
https://www.youtube.com/watch?v=MfeCHPBfeFA&feature=youtu.be A video to show you

**Comment by BONNe** [comment]
Oh yea... that cannot be changed :(

Mojang biome is set to 4x4x4 blocks. You cannot set it to each block. 

So basically, if you want to avoid overwriting biome in greenhouses, you need to create it to with coordinates that can be divided by 4 in all 3 dimensions :(

**Comment by tastybento** [comment]
Yes, Mojang also "blend" the biomes now, so they have irregular shapes at the borders.

**Comment by KlayaR** [comment]
Okay. Thank you =D
