### ISSUE TITLE
adding more permissions customization per chunk biome generation

### ISSUE THREAD

**Issue by SergusWhite** [BentoBoxWorld/Biomes#81]
#### Is your feature request related to a problem?

Permissions doesn't to give players the ability to make certain changes to the biomes on their island, chunk or block.
It's either the player has all the permissions or he doesnt at all.
Just like with silkspawners.

#### Describe the solution you'd like us to implement.

add permissions for each ability and per biome possible.

island overworld ; all biomes
Island overworld chunk; all biomes
island overworld block; all biomes
island nether ; all biomes
Island nether chunk; all biomes
island nether block; all biomes
island end ; all biomes
Island end; all biomes
island end; all biomes

**Comment by BONNe** [comment]
I am not keen on implementing it per dimension, as in general, it does not make sense in the Biomes environment.
I will think about implementing the specification per biome, as in general, it would cover also the environmental cases.

So... how I would like to implement it:

There are 3 main permissions:
- [gamemode].biomes.set.ISLAND.* - default: true
- [gamemode].biomes.set.RANGE.* - default: true
- [gamemode].biomes.set.CHUNK.* - default: true

If the player does not have this permission, he cannot use these options, and they will not show up in the GUI. 
If none of the permissions are given to the player, he cannot change biomes at all.

If * is replaced with a BiomeObject ID, then the player can use this option for that biome. All others will not be allowed to be used. That means, to use a biome set to all biomes, the admin will need to manually add permission to the player with BiomeObject Id at the end.

Will this work for you?

**Comment by SergusWhite** [comment]
Yes thank you

**Comment by BONNe** [comment]
I skipped GUI changes, as GUI will be reworked.
