### ISSUE TITLE
Range biomes

### ISSUE THREAD

**Issue by Pikachu2p** [BentoBoxWorld/Biomes#88]
I faced such a problem. When I change the biome through the range within a radius of 5 blocks, which is set in config, when I move to the server, but nothing changes. But when I change through island or chunk, the biome changes for the ENTIRE island. But there is a range that says that the biome has changed, but nothing changes when re-entering. :(

 paper 1.15.2
biomes-1.14.0
bskyblock-1.14.3.

There are no errors or warnings in the console

**Comment by BONNe** [comment]
This issue is not relevant anymore.

The issue was with timing when 3D biomes were still in the implementation phase, and it did not work with 2D biomes in 1.15.2
