### ISSUE TITLE
Unlockable Biomes by Items

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Biomes#9]
#### Is your feature request related to a problem? Please describe.
Challenge plugins allows to complete some challenges if required items are collected. It would be nice, if also biomes could be unlocked only when certain items are in user inventory.

#### Describe the solution you'd like
Add ability to unlock biomes if specified items are in user inventory.

#### Describe alternatives you've considered
As it could be waist full to implement the same behavior in 2 different addons, probably implementing #8 and adding permission to challenge in ChallengesAddon would be much better.

#### Additional context
None

**Comment by Poslovitch** [comment]
What about just creating commands for this? Or maybe some sort of API methods - this would need to update Challenges to use them, but that shouldn't be that much of a trouble.
